import type {
  GameEngine,
  Player,
  PythonBoard,
  PythonMove,
} from "@/game/engine-v2";
import {
  extendsStrategicBest,
  mergeStrategicBest,
  strategicProgress,
  type StrategicProgress,
} from "./strategic-progress";

export type MaybePromise<T> = T | Promise<T>;

export interface SelfPlayDecisionContext {
  /** A disposable copy of the current board. Do not retain it after selectMove returns. */
  board: PythonBoard;
  legalMoves: readonly PythonMove[];
  player: Player;
  turnNumber: number;
  actionsTaken: number;
  forcedAutomaticCapture: boolean;
  random: () => number;
  signal?: AbortSignal;
}

export interface SelfPlayAgent {
  id: string;
  selectMove(
    context: SelfPlayDecisionContext
  ): MaybePromise<PythonMove | string>;
}

export interface SelfPlayMoveRecord {
  uci: string;
  name: PythonMove["name"];
  automaticCapture: boolean;
  /** One through three for player actions; omitted for automatic captures. */
  actionNumber?: number;
}

export interface SelfPlayTurnRecord {
  turnNumber: number;
  player: Player;
  startFen: string;
  endFen: string;
  moves: SelfPlayMoveRecord[];
  /** False only when a safety limit stopped the game in the middle of a turn. */
  completed: boolean;
}

export interface SelfPlayOutcome {
  winner?: Player;
  termination: string;
}

export interface PlayOneGameConfig {
  /** Reuse one loaded engine for a batch; loading Pyodide once per game is expensive. */
  engine: GameEngine;
  red: SelfPlayAgent;
  blue: SelfPlayAgent;
  fen?: string;
  /** Maximum number of player turns, including a terminal partial turn. */
  maxTurns?: number;
  /** Safety valve for malformed agents or engines that never finish a turn. */
  maxDecisions?: number;
  /** Exact position occurrence that ends the game as a draw. Defaults to threefold. */
  repetitionLimit?: number;
  /** Completed turns without material or a new strategic landmark. Defaults to 36. */
  noProgressTurns?: number;
  /** Unsigned 32-bit seed. The generated seed is returned when omitted. */
  seed?: number;
  signal?: AbortSignal;
  onTurn?: (turn: SelfPlayTurnRecord) => MaybePromise<void>;
}

export interface SelfPlayGameResult {
  seed: number;
  redAgentId: string;
  blueAgentId: string;
  initialFen: string;
  finalFen: string;
  turns: SelfPlayTurnRecord[];
  outcome: SelfPlayOutcome;
  completed: boolean;
  moveCount: number;
  actionCount: number;
  automaticCaptureCount: number;
}

const DEFAULT_MAX_TURNS = 400;
const DEFAULT_REPETITION_LIMIT = 3;
const DEFAULT_NO_PROGRESS_TURNS = 36;

function playerToMove(board: PythonBoard): Player {
  return board.is_red_turn() ? "RED" : "BLUE";
}

function outcomeFromBoard(board: PythonBoard): SelfPlayOutcome | undefined {
  const outcome = board.outcome();
  if (!outcome) return undefined;
  try {
    return {
      winner:
        outcome.winner === false
          ? "RED"
          : outcome.winner === true
          ? "BLUE"
          : undefined,
      termination: outcome.termination,
    };
  } finally {
    destroyProxy(outcome);
  }
}

function checkedPositiveInteger(value: number, label: string): number {
  if (!Number.isSafeInteger(value) || value <= 0) {
    throw new RangeError(`${label} must be a positive integer`);
  }
  return value;
}

function resolveSeed(seed: number | undefined): number {
  const value = seed ?? Math.floor(Math.random() * 0x1_0000_0000);
  if (!Number.isSafeInteger(value) || value < 0 || value > 0xffff_ffff) {
    throw new RangeError("seed must be an unsigned 32-bit integer");
  }
  return value >>> 0;
}

/** Small deterministic PRNG suitable for reproducible move sampling. */
export function createSeededRandom(seed: number): () => number {
  let state = seed >>> 0;
  return () => {
    state = (state + 0x6d2b79f5) | 0;
    let value = Math.imul(state ^ (state >>> 15), 1 | state);
    value ^= value + Math.imul(value ^ (value >>> 7), 61 | value);
    return ((value ^ (value >>> 14)) >>> 0) / 0x1_0000_0000;
  };
}

export function createRandomAgent(id = "random"): SelfPlayAgent {
  return {
    id,
    selectMove: ({ legalMoves, random }) => {
      if (legalMoves.length === 0) {
        throw new Error("Random agent received no legal moves");
      }
      return legalMoves[Math.floor(random() * legalMoves.length)];
    },
  };
}

function destroyProxy(value: unknown): void {
  const destroy = (value as { destroy?: () => void } | undefined)?.destroy;
  if (typeof destroy === "function") destroy.call(value);
}

function abortIfRequested(signal?: AbortSignal): void {
  if (signal?.aborted) {
    const error = new Error("Self-play game aborted");
    error.name = "AbortError";
    throw error;
  }
}

async function notifyTurn(
  callback: PlayOneGameConfig["onTurn"],
  turn: SelfPlayTurnRecord
): Promise<void> {
  if (callback) await callback(turn);
}

/**
 * Play one headless game by asking agents to choose among moves generated by
 * the production Python engine. This function does not reproduce any GHQ
 * legality, capture, action-limit, turn-transition, or game-over rule.
 */
export async function playOneGame(
  config: PlayOneGameConfig
): Promise<SelfPlayGameResult> {
  const maxTurns = checkedPositiveInteger(
    config.maxTurns ?? DEFAULT_MAX_TURNS,
    "maxTurns"
  );
  const maxDecisions = checkedPositiveInteger(
    config.maxDecisions ?? maxTurns * 64,
    "maxDecisions"
  );
  const repetitionLimit = checkedPositiveInteger(
    config.repetitionLimit ?? DEFAULT_REPETITION_LIMIT,
    "repetitionLimit"
  );
  const noProgressTurns = checkedPositiveInteger(
    config.noProgressTurns ?? DEFAULT_NO_PROGRESS_TURNS,
    "noProgressTurns"
  );
  const seed = resolveSeed(config.seed);
  const random = createSeededRandom(seed);
  const board = config.engine.BaseBoard(config.fen);
  const turns: SelfPlayTurnRecord[] = [];
  const initialFen = board.board_fen();
  let currentTurn: SelfPlayTurnRecord | undefined;
  let decisionCount = 0;
  let actionCount = 0;
  let automaticCaptureCount = 0;
  let finalOutcome: SelfPlayOutcome | undefined;
  let turnsWithoutProgress = 0;
  const strategicBest: Record<Player, StrategicProgress> = {
    RED: strategicProgress(initialFen, "RED"),
    BLUE: strategicProgress(initialFen, "BLUE"),
  };
  const positionOccurrences = new Map<string, number>([[board.serialize(), 1]]);

  const finishCurrentTurn = async (completed: boolean) => {
    if (!currentTurn) return;
    currentTurn.endFen = board.board_fen();
    currentTurn.completed = completed;
    turns.push(currentTurn);
    await notifyTurn(config.onTurn, currentTurn);
    if (completed && !finalOutcome) {
      const currentStrategicProgress = strategicProgress(
        currentTurn.endFen,
        currentTurn.player
      );
      const madeStrategicProgress = extendsStrategicBest(
        strategicBest[currentTurn.player],
        currentStrategicProgress
      );
      strategicBest[currentTurn.player] = mergeStrategicBest(
        strategicBest[currentTurn.player],
        currentStrategicProgress
      );
      const madeProgress = madeStrategicProgress || currentTurn.moves.some(
        (move) =>
          move.name === "Reinforce" ||
          move.automaticCapture ||
          move.uci.includes("x")
      );
      turnsWithoutProgress = madeProgress ? 0 : turnsWithoutProgress + 1;
      const positionKey = board.serialize();
      const occurrences = (positionOccurrences.get(positionKey) ?? 0) + 1;
      positionOccurrences.set(positionKey, occurrences);
      if (occurrences >= repetitionLimit) {
        finalOutcome = { termination: "repetition" };
      } else if (turnsWithoutProgress >= noProgressTurns) {
        finalOutcome = { termination: "no-progress" };
      }
    }
    currentTurn = undefined;
  };

  try {
    abortIfRequested(config.signal);
    finalOutcome = outcomeFromBoard(board);

    while (!finalOutcome) {
      abortIfRequested(config.signal);

      if (!currentTurn && turns.length >= maxTurns) {
        finalOutcome = { termination: "max-turns" };
        break;
      }
      if (decisionCount >= maxDecisions) {
        await finishCurrentTurn(false);
        finalOutcome = { termination: "max-decisions" };
        break;
      }

      const player = playerToMove(board);
      if (!currentTurn) {
        currentTurn = {
          turnNumber: turns.length + 1,
          player,
          startFen: board.board_fen(),
          endFen: board.board_fen(),
          moves: [],
          completed: false,
        };
      }

      const decisionBoard = board.copy();
      const generatedMoves = decisionBoard.generate_legal_moves();
      const legalMoves = Array.from(generatedMoves);
      destroyProxy(generatedMoves);
      if (legalMoves.length === 0) {
        legalMoves.forEach(destroyProxy);
        destroyProxy(decisionBoard);
        finalOutcome = outcomeFromBoard(board);
        if (finalOutcome) {
          await finishCurrentTurn(true);
          break;
        }
        throw new Error(
          `Production engine returned no legal moves without an outcome on turn ${currentTurn.turnNumber}`
        );
      }

      const legalUcis = new Set(legalMoves.map((move) => move.uci()));
      const forcedAutomaticCapture = legalMoves.every(
        (move) => move.name === "AutoCapture"
      );
      const agent = player === "RED" ? config.red : config.blue;
      let selectedUci: string;
      try {
        const selected = await agent.selectMove({
          board: decisionBoard,
          legalMoves,
          player,
          turnNumber: currentTurn.turnNumber,
          actionsTaken: board.turn_moves,
          forcedAutomaticCapture,
          random,
          signal: config.signal,
        });
        selectedUci =
          typeof selected === "string" ? selected : selected?.uci?.();
      } finally {
        legalMoves.forEach(destroyProxy);
        destroyProxy(decisionBoard);
      }

      if (!selectedUci || !legalUcis.has(selectedUci)) {
        throw new Error(
          `${agent.id} selected illegal move ${JSON.stringify(
            selectedUci
          )} for ${player} on turn ${currentTurn.turnNumber}`
        );
      }

      const move = config.engine.Move.from_uci(selectedUci);
      try {
        if (!board.is_legal(move)) {
          throw new Error(
            `${agent.id} selected stale move ${selectedUci} for ${player} on turn ${currentTurn.turnNumber}`
          );
        }

        const automaticCapture = move.name === "AutoCapture";
        const moveRecord: SelfPlayMoveRecord = {
          uci: selectedUci,
          name: move.name,
          automaticCapture,
        };
        if (automaticCapture) {
          automaticCaptureCount++;
        } else {
          actionCount++;
          moveRecord.actionNumber = board.turn_moves + 1;
        }

        const previousPlayer = player;
        board.push(move);
        currentTurn.moves.push(moveRecord);
        decisionCount++;

        finalOutcome = outcomeFromBoard(board);
        const playerChanged = playerToMove(board) !== previousPlayer;
        if (finalOutcome || playerChanged) {
          await finishCurrentTurn(true);
        }
      } finally {
        destroyProxy(move);
      }
    }

    return {
      seed,
      redAgentId: config.red.id,
      blueAgentId: config.blue.id,
      initialFen,
      finalFen: board.board_fen(),
      turns,
      outcome: finalOutcome ?? { termination: "unknown" },
      completed:
        finalOutcome !== undefined &&
        finalOutcome.termination !== "max-turns" &&
        finalOutcome.termination !== "max-decisions",
      moveCount: decisionCount,
      actionCount,
      automaticCaptureCount,
    };
  } finally {
    destroyProxy(board);
  }
}
